services:
  url-shortener:
    build: .
    ports:
      - "80:80"
    depends_on:
      - url-shortener-url-shortener-pg-1

  url-shortener-url-shortener-pg-1:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - docker.env
    ports:
      - "5432:5432"
