version: "3.9"
services:
  url-shortener:
    build: .
    ports:
      - "80:80" 
    # Incase i want to keep shortneed urls in a database in future
    # depends_on:
    #   - my-database
  # my-database:
  #   image: postgres:latest 
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase